### ISSUE TITLE
build is error out with 'Error: spawn E2BIG'

### ISSUE THREAD

**Issue by katemenkhaus** [predix-ui/predix-ui.github.io#37]
The build is being stopped in travis by this error: 
Error: spawn E2BIG
    at exports._errnoException (util.js:949:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:367:9)
    at Object.exports.execFile (child_process.js:139:15)
    at exports.exec (child_process.js:99:18)
    at DestroyableTransform.flush [as _flush] (/home/travis/build/predix-ui/predix-ui.github.io/node_modules/gulp-git/lib/add.js:30:5)
    at DestroyableTransform.<anonymous> (/home/travis/build/predix-ui/predix-ui.github.io/node_modules/gulp-git/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)

seems to occur in the  gulp.task('gitStuff', function() {};

**Comment by runn-vermel** [comment]
fixed in v0.2.9
